config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#index'
  get 'static_pages/show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/static_pages_controller.rb
require 'flickr'

class StaticPagesController < ApplicationController
  def index
  end

  def show
    flickr_id = params[:flickr_id]

    flickr = Flickr.new

    @photos = flickr.photos.search(:user_id => flickr_id.values[0], :api_key => ENV['FLICKR_API_KEY'])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickrApi</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/index.html.erb
<%= form_for :flickr_id, url: static_pages_show_path, method: 'get' do |f| %>
  <p>
    <%= f.label 'user_id: ' %>
    <%= f.text_field :flickr_id %>  
  </p>

  <p>
    <%= f.submit 'submit' %>
  </p>
  
<% end %>

app/views/static_pages/show.html.erb
<% @photos.each do |photo| %>
  <% id = photo['id'] %>
  <% server_id = photo['server'] %>
  <% secret = photo['secret'] %>
  <% url = "https://live.staticflickr.com/#{server_id}/#{id}_#{secret}.jpg" %>
  <img src=<%= url %> alt="">
<% end %>